```{r}
library(dplyr)
library(tidyverse)
library(caret) # For downsample function
library(caTools) # used for spiting samples
library(OneR) # for bin function
library(kernlab) # For various Svm kernerls
library(DMwR) # For Smote function
library(ROCR) # For ROC curve
library(gplots) # For gplots
library(e1071)  # for naive bayes model
```
```{r}
# I have given the path of my machine where the dataset has kept.It should be a relative path with CC.csv.
CreditCardDF <- read.csv("/Users/him/Desktop/Important Docs/NCI/Academic courses/Data mining and machine learning/Clg_Project/dataset/Finalized dataset/CC.csv")
#Header of Data
head(CreditCardDF)
# Checking if there are any null values in my dataset colums
print(sum(is.na(CreditCardDF))) # There are no Na values 
# As mentioned in the interim project report also , PCA has already done on this dataset so that is the reason
print(str(CreditCardDF))
print(table(CreditCardDF$Class))
```
```{r}
# As we need to change numerical data into categorical data for Naive Bayes using binning
str(bin(CreditCardDF)) # We can see that all independent variables have levels 5
binedData <- bin(CreditCardDF, nbins = 5, labels = NULL, method ="length", na.omit = TRUE)
binedData$Class <- factor(binedData$Class , levels = c(0,1) , labels = c("False","True"))
# Checking for the imbalaced classification 
as.data.frame(table(binedData$Class))
```
```{r}
# Split dataset 
ccdf_split <- sample.split(binedData$Class , SplitRatio = 0.8)
training_dataCC <- subset(binedData , ccdf_split== TRUE)
test_dataCC <- subset(binedData , ccdf_split== FALSE)
table(training_dataCC$Class)
```
```{r}
# Train Model on all training data
set.seed(5627)
svm_classifier_Train <- ksvm(Class ~ ., data = training_dataCC,kernel = "vanilladot")
PredictModel <- predict(svm_classifier_Train, newdata = test_dataCC)
train.svm.cm <- confusionMatrix(PredictModel,data = test_dataCC$Class)
# Plot confusion Matrix
fourfoldplot(train.svm.cm$table, color = c("blue", "yellow"), conf.level = 0, margin = 1, main = "Confusion Matrix for Model") 
summary(PredictModel) # you can observe the accuracy.
```

```{r}
# Using Sampling methods for imbalaced classification.
# Using SMOTE method 
smoteSampling_train <- SMOTE(Class ~., training_dataCC, perc.over = 5000, k = 5, perc.under = 500)
table(smoteSampling_train$Class)
ggplot(smoteSampling_train, aes(Class)) + geom_bar(fill = "red")+theme_bw()+
  coord_flip()+ labs(title = "Bar Chart") + theme_gray()
# Using downSampling technique 
downsampling_train <- downSample(x = training_dataCC[, -ncol(training_dataCC)],y = training_dataCC$Class)
table(downsampling_train$Class)
ggplot(downsampling_train, aes(Class)) + geom_bar(fill = "red")+theme_bw()+
  coord_flip()+ labs(title = "Bar Chart") + theme_gray()
```
```{r}
# Train Model on Smote sampled data
set.seed(5627)
# Using Vanilladot
svm_classifier_vanilladot <- ksvm(Class ~ ., data = smoteSampling_train,kernel = "vanilladot")
PredictModelSVMV <- predict(svm_classifier_vanilladot, newdata = test_dataCC)
svm.cm.van <- confusionMatrix(PredictModelSVMV,data = test_dataCC$Class)
# Summary
summary(PredictModelSVMV)
# Plot confusion Matrix
fourfoldplot(svm.cm.van$table, color = c("Red", "Green"), conf.level = 0, margin = 1, main = "Confusion Matrix for Model using Vanilladot svm kernel")  
#Using rbfdot
svm_classifier_rbfdot <- ksvm(Class ~ ., data = smoteSampling_train,kernel = "rbfdot")
PredictModelSVMR <- predict(svm_classifier_rbfdot, newdata = test_dataCC)
svm.cm.rbf <- confusionMatrix(PredictModelSVMR,data = test_dataCC$Class)
#Summary
summary(PredictModelSVMR)
# Plot confusion Matrix
fourfoldplot(svm.cm.rbf$table, color = c("Red", "Green"), conf.level = 0, margin = 1, main = "Confusion Matrix for Model using rbfdot svm")
```
```{r}
# Train Model on down sampled data
set.seed(5627)
down_svm_classifier <- ksvm(Class ~ ., data = downsampling_train,kernel = "vanilladot" )
down_PredictModel <- predict(down_svm_classifier, newdata = test_dataCC)
down.svm.cm <- confusionMatrix(down_PredictModel,data = test_dataCC$Class)
# Plot confusion Matrix
fourfoldplot(down.svm.cm$table, color = c("Red", "Green"), conf.level = 0, margin = 1, main = "Confusion Matrix for Model")
summary(down_PredictModel)
```




```{r}
# Train on Downsampled data using SVM linear method including K-fold technique
set.seed(5627)
svm_ctrl <- trainControl(method = "repeatedcv", repeats = 5,classProbs = TRUE,summaryFunction = twoClassSummary)
svm_Linear <- train(Class ~., data = downsampling_train, method = "svmLinear",trControl=svm_ctrl,preProcess = c("center", "scale"),metric = "ROC" ,tuneLength = 10)
PredictMod <- predict(svm_Linear, newdata = test_dataCC)
svmLinear.cm <- confusionMatrix(PredictMod,data = test_dataCC$Class)
#
fourfoldplot(svmLinear.cm$table, color = c("Red", "Green"), conf.level = 0, margin = 1, main = "Confusion Matrix for Model") 
summary()
```

```{r}
# Naive Bayes Model Implementation
set.seed(5627)
table(smoteSampling_train$Class)
# Train Model
nbModel_fit=naiveBayes(smoteSampling_train$Class ~., data=smoteSampling_train )
# Model Prediction and Evaluation
PredictMod_NB <- predict(nbModel_fit, newdata = test_dataCC[-32])
nb.cm <- confusionMatrix(PredictMod_NB,data = test_dataCC$Class)
nb.cm$byClass
# Plot confusion matrix
fourfoldplot(nb.cm$table, color = c("Red", "Green"), conf.level = 0, margin = 1, main = "Confusion Matrix for Naive Bayes Model")
```






